apiVersion: apps/v1
kind: Deployment
metadata:
   name: sql-deploy
   labels:
      app: sql

spec:
 replicas: 1
 selector:
  matchLabels:
   app: sql
 template:
    metadata:
     labels:
       app: sql
    spec:
      containers:
         - name: sql-deploy
           image: rkatrap/sql  
           env: 
              - name: MYSQL_ROOT_PASSWORD
                value: "admin"
              - name: MYSQL_DATABASE
                value: "mydb"
              - name: MYSQL_USER
                value: "admin"
              - name: MYSQL_PASSWORD
                value: "admin"
           ports:
               - containerPort: 3306
           volumeMounts:
               - name: mysqldata
                 mountPath: /docker-entrypoint-initdb.d/     
      volumes: 
         - name: mysqldata
           persistentVolumeClaim: 
            claimName: mysql-pvc       
             
                                    


